Add test cases and examples of App Configuration.
isra-fel/azure-powershell pull request #6
Opened 2020-07-22 07:07 UTC by LucasYao93

## Description

Add test cases and examples of App Configuration.

2020-07-22 09:04 UTC, isra-fel requested changes

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/custom/Update-AzAppConfigurationStore.ps1
> +.LINK
👍

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Get-AzAppConfigurationStore.md
> +----          ----
```suggestion
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/New-AzAppConfigurationStore.md
> +This command creates an app configuration with the IdentityType set to "UserAssigned".
```suggestion
This command creates an app configuration and assign a user-assigned managed identity to it.
See the example of `Update-AzAppConfigurationStore` for the following steps to enable CMK (cusomer managed key).
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/New-AzAppConfigurationStore.md
> +This command creates an app configuration with the IdentityType set to "SystemAssigned".
```suggestion
This command creates an app configuration and enables the system-assigned managed identity associated with the resource.
See the example of `Update-AzAppConfigurationStore` for the following steps to enable CMK (cusomer managed key).
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/New-AzAppConfigurationStore.md
> +This command creates an app configuration with the IdentityType set to "SystemAssigned, UserAssigned".
```suggestion
You can enable system-assigned managed identity and give user-assigned identities at the same time.
See the example of `Update-AzAppConfigurationStore` for the following steps to enable CMK (cusomer managed key).
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/New-AzAppConfigurationStoreKey.md
> +### Example 1: Regenerate key of an app configuration store by object
```suggestion
### Example 2: Regenerate key of an app configuration store by object
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Test-AzAppConfigurationStoreNameAvailability.md
> +### Example 1: Test availability of the application configuration store name
```suggestion
### Example 1: Test availability of the app configuration store name
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Test-AzAppConfigurationStoreNameAvailability.md
> +This command tests availability of the application configuration store name.
```suggestion
This command tests availability of the app configuration store name.
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +### Example 1: Update encryption key of an app conifguration store that IdentityType is "SystemAssigned"
```suggestion
### Example 1: Enable data encryption of the app conifguration store by system-assigned managed identity
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +This command updates encryption key of an app conifguration store that IdentityType is "UserAssigned".
```suggestion
This command enables data encryption by a key stored in Azure Key Vault using a system-assigned managed identity.
The vault must have enabled soft-delete and purge-protection, and the managed identity must have these key permissions: get, wrapKey, unwrapKey.
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +### Example 2: Update encryption key of an app conifguration store that IdentityType is "UserAssigned"
```suggestion
### Example 2: Enable data encryption of the app conifguration store by user-assigned managed identity
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +This command updates encryption key of an app conifguration store that IdentityType is "SystemAssigned".
```suggestion
This command enables data encryption by a key stored in Azure Key Vault using a user-assigned managed identity.
The user-assigned identity must have been set with `-UserAssignedIdentity`.
The vault must have enabled soft-delete and purge-protection, and the managed identity must have these key permissions: get, wrapKey, unwrapKey.
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +### Example 3: Update encryption key to null of an app conifguration store by pipeline.
```suggestion
### Example 3: Disable encryption
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +PS C:\> $appConf = Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test -Name appconfig-test10 | Update-AzAppConfigurationStore -EncryptionKeyIdentifier $null
```suggestion
PS C:\> Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test -Name appconfig-test10 | Update-AzAppConfigurationStore -EncryptionKeyIdentifier $null
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +This command updates encryption key to null of an app conifguration store.
```suggestion
To disable encryption, set `EncryptionKeyIdentifier` to `$null`.
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +### Example 3: Update sku and tag of an app conifguration store by pipeline.
```suggestion
### Example 4: Update sku and tag of an app conifguration store by pipeline.
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +PS C:\> $appConf = Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test -Name appconfig-test10 | Update-AzAppConfigurationStore -Sku 'standard' -Tag @{'key'='update'}
```suggestion
PS C:\> Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test -Name appconfig-test10 | Update-AzAppConfigurationStore -Sku 'standard' -Tag @{'key'='update'}
```

2020-07-22 09:04 UTC, isra-fel commented on src/AppConfiguration/test/test-plan.ps1
>  # 2.2 Enable encryption using system-assigned identity (-EncryptionKeyIdentifier https://yemingac.vault.azure.net/keys/encryptionkey/10f3811b78a24208ae5ebbfe18983f6d)
You can delete this file.

2020-07-22 09:13 UTC, LucasYao93 commented on src/AppConfiguration/examples/Get-AzAppConfigurationStore.md
> +----          ----
Done

2020-07-22 09:14 UTC, LucasYao93 commented on src/AppConfiguration/examples/New-AzAppConfigurationStore.md
> +This command creates an app configuration with the IdentityType set to "UserAssigned".
Done

2020-07-22 09:15 UTC, LucasYao93 commented on src/AppConfiguration/examples/New-AzAppConfigurationStore.md
> +This command creates an app configuration with the IdentityType set to "SystemAssigned, UserAssigned".
Done

2020-07-22 09:16 UTC, LucasYao93 commented on src/AppConfiguration/examples/New-AzAppConfigurationStoreKey.md
> +### Example 1: Regenerate key of an app configuration store by object
Done

2020-07-22 09:17 UTC, LucasYao93 commented on src/AppConfiguration/examples/Test-AzAppConfigurationStoreNameAvailability.md
> +### Example 1: Test availability of the application configuration store name
Done

2020-07-22 09:17 UTC, LucasYao93 commented on src/AppConfiguration/examples/Test-AzAppConfigurationStoreNameAvailability.md
> +This command tests availability of the application configuration store name.
Done

2020-07-22 09:27 UTC, LucasYao93 commented on src/AppConfiguration/test/test-plan.ps1
>  # 2.2 Enable encryption using system-assigned identity (-EncryptionKeyIdentifier https://yemingac.vault.azure.net/keys/encryptionkey/10f3811b78a24208ae5ebbfe18983f6d)
Done

2020-07-22 09:27 UTC, LucasYao93 commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +PS C:\> $appConf = Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test -Name appconfig-test10 | Update-AzAppConfigurationStore -Sku 'standard' -Tag @{'key'='update'}
Done

2020-07-22 09:28 UTC, LucasYao93 commented on src/AppConfiguration/examples/New-AzAppConfigurationStore.md
> +This command creates an app configuration with the IdentityType set to "SystemAssigned".
Done

2020-07-22 09:28 UTC, LucasYao93 commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +PS C:\> $appConf = Get-AzAppConfigurationStore -ResourceGroupName azpwsh-manual-test -Name appconfig-test10 | Update-AzAppConfigurationStore -EncryptionKeyIdentifier $null
Done

2020-07-22 09:28 UTC, LucasYao93 commented on src/AppConfiguration/examples/Update-AzAppConfigurationStore.md
> +This command updates encryption key to null of an app conifguration store.
Done

2020-07-23 02:27 UTC, isra-fel approved these changes
LGTM

2020-07-23 02:27 UTC, merged